shell detection: drop etc_passwd parsing
This breaks on macOS:

```
   Compiling etc-passwd v0.2.0
error[E0027]: pattern does not mention fields `pw_change`, `pw_class`, `pw_expire`
  --> /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/etc-passwd-0.2.0/src/lib.rs:89:13
   |
89 |           let libc::passwd {
   |  _____________^
90 | |             pw_name,
91 | |             pw_passwd,
92 | |             pw_uid,
...  |
96 | |             pw_shell,
97 | |         } = *passwd;
   | |_________^ missing fields `pw_change`, `pw_class`, `pw_expire`
   |
help: include the missing fields in the pattern
   |
96 |             pw_shell, pw_change, pw_class, pw_expire } = *passwd;
   |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
help: if you don't care about these missing fields, you can explicitly ignore them
   |
96 |             pw_shell, .. } = *passwd;
   |                     ~~~~~~

For more information about this error, try `rustc --explain E0027`.
error: could not compile `etc-passwd` due to previous error
```

We should probably report an issue upstream and then come back to it.